# Generated by Django 3.0.7 on 2020-07-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mail',
        ),
        migrations.AddField(
            model_name='profile',
            name='quotes',
            field=models.TextField(default=' ', max_length=350),
            preserve_default=False,
        ),
    ]
