# Generated by Django 3.0.7 on 2020-07-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200715_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Event Name')),
                ('venue', models.CharField(max_length=120)),
                ('manager', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
